Task 1 - Helloworld
Sydney-Informatics-Hub/fastqc-nf pull request #4
Opened 2023-09-29 02:36 UTC by chlu0571

2023-09-29 02:39 UTC, chlu0571 commented
I had created 3 main.nf (main/ main-1/ main-2) to perform the helloworld task. Can you check my scripts and tell me what to improve for the scripts? Thank you.

2023-09-29 02:47 UTC, georgiesamaha requested changes
A few things before I can test: 

1. Create a file in the main directory fastqc-nf called `.gitignore` and add the following to it. This will ensure you dont push all your nextflow logs and hidden files to the repo: 

```bash
.nextflow*
work/
```

2. Write some instructions in the User Guide section of the README.md file so I know how to execute the scripts. We can overwrite this section of the README.md for each new build you do. Can you write instructions using [markdown format](https://www.markdownguide.org/basic-syntax/), so include code inside code blocks.

2023-10-13 05:40 UTC, georgiesamaha requested changes
Having your `nextflow.config` file inside the `fastqc-nf` directory will automatically apply it to your workflow execution. When I executed your second example command after executing the first, I got this message. Inside the `nextflow.config`, you're setting resource allocations, creating execution report, timeline, and trace files, and defining profiles. All files were saved to a directory called `results`. 

```
N E X T F L O W  ~  version 22.10.3
Launching `main-2.nf` [hungry_austin] DSL2 - revision: ba63f412ba
Trace file already exists: /home/ubuntu/fastqc-nf/results/runInfo/trace.txt -- enable the relevant `overwrite` option in your config file to overwrite existing files
```

Before we implement workflow configuration, might be worth deleting the `nextflow.config` from the repo and copying it across only when you are ready to apply it to your workflow.

2023-10-13 05:40 UTC, georgiesamaha commented on README.md
Lets follow the general structure of this [workflow documentation guide](https://github.com/AustralianBioCommons/doc_guidelines/blob/master/documentation_templates/workflows.md). Don't have to contain all sections, just the necessary ones. See [here](https://github.com/Sydney-Informatics-Hub/Germline-StructuralV-nf) for an example.

2023-10-13 05:40 UTC, georgiesamaha commented on README.md
> +nextflow run -e.mode=ciao main-1.nf
What is the reasoning behind using `-e.mode`? I've never seen this before. Can you instead define a parameter at the top of `main.nf` called hello and apply it to the workflow with `nextflow run main.nf --hello ciao`

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
Can you please include the whole structure of this `main.nf` template with the help message, log info, comment lines, and execution summary? Have added additional comments below re: what to keep and what to adjust.

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -"""
Keep this section, just adjust as required. For example: 

```
=======================================================================================
FastQC-nf
=======================================================================================
Created by Sydney Informatics Hub, University of Sydney  
Find documentation @ https://github.com/Sydney-Informatics-Hub/fastqc-nf
Cite this pipeline @ 
=======================================================================================
Workflow run parameters 
=======================================================================================
input       : ${params.hello}
workDir     : ${workflow.workDir}
=======================================================================================
```

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -/// Help function
Keep this comment line, same reason as above.

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
>  }
Keep this also, again adjust contents as required, for example: 

```
  Usage:  nextflow run main.nf --hello ciao
  Required Arguments:
  --hello Version of hello. If there are limited options here, specify what they are. 
```

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -// Define workflow structure. Include some input/runtime tests here.
Keep this comment line, same reason as above.

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -// Show help message if --help is run or (||) a required parameter (input) is not provided
Keep this comment line, same reason as above.

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -	exit 1
This section will print your help message defined above. Keep it to print to the screen when you run `nextflow run main.nf --help`

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -// If none of the above are a problem, then run the workflow
Keep this comment line, same reason as above.

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -}
Keep all of this to summarise workflow success. Remove outDir for this example.

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -} else {
Include this to run your pipeline if you do not use `--help`. You will need to include `Channel.of('Ciao', 'Hello', 'Hola') | helloworld | view` after it.

2023-10-13 05:40 UTC, georgiesamaha commented on main.nf
> -// Define channels
Keep this comment line, same reason as above.

2023-10-19 03:41 UTC, closed without merging