Fastqc2
Sydney-Informatics-Hub/fastqc-nf pull request #5
Opened 2023-10-05 06:55 UTC by chlu0571

perform fastqc in one fastq file

2023-10-13 05:41 UTC, georgiesamaha commented
To request a review from me, instead of assigning this PR to me, just click request review in the top section of the menu on the right side of this page.

2023-10-13 06:33 UTC, georgiesamaha reviewed
Looks beautiful! Very tidy :) Can you make a few small changes and also in your documentation, link me to where i can find the fq file you're using. Just good practice to give explicit directions to anyone running your code, even for finding test data.

2023-10-13 06:33 UTC, georgiesamaha commented on README.md
> +'''
Remove this, I believe you :)

2023-10-13 06:33 UTC, georgiesamaha commented on main.nf
>  #!/usr/bin/env nextflow
Same comments here as for hello world. Can you keep the comment lines in your scripts so we know what the code sections are doing at a basic level.

2023-10-13 06:33 UTC, georgiesamaha commented on main.nf
> +    container "/home/ubuntu/singularity-hpc"
how does this link to the fastqc container? Could you instead specify more like [this](https://github.com/Sydney-Informatics-Hub/IndexReferenceFasta-nf/blob/b1de54a594e2f11295c9cd41be8b03d991bd4883/modules/gatk.nf#L4)

2023-10-13 06:33 UTC, georgiesamaha commented on main.nf
> +    #!/usr/bin/bash
Can remove this line I think.

2023-10-13 06:33 UTC, georgiesamaha commented on main.nf
> +// nextflow run main.nf --fq NA12877_R1_10k.fq.gz --output results
Add this to directions in `README.md`

2023-10-17 23:37 UTC, georgiesamaha commented on main.nf
> +    container "/home/ubuntu/singularity-hpc"
search for the fastqc biocontainer in https://quay.io/ and provide to container scope i.e:
```
container "quay.io/biocontainers/fastqc:0.12.1--hdfd78af_0" 
```

* Nextflow will pull a container for you automatically when you run a workflow
* TODO later look at what to do about pulling containers when your job has no external network access 
* When using Singularity to manage containers with nextflow, dont need to clarify it is a docker container. For example when pulling a Docker container with Singularity normally you would use: 
```
singularity pull docker://quay.io/biocontainers/fastqc:0.12.1--hdfd78af_0
```

2023-10-17 23:39 UTC, georgiesamaha requested changes
Clarified how to specify a container

2023-10-20 02:09 UTC, chlu0571 commented
Hi Georgie, Can you run with " nextflow run main.nf --fq ./data/NA12877_R1_10k.fq.gz --output results". I modified Readme and left previous scripts in task directory.

2023-10-23 02:46 UTC, georgiesamaha commented
Hi @chlu0571, a few things I did and why: 

1. The code didnt run following your instructions, so I rewrote `main.nf` with functioning process 
2. I couldn't execute the singularity container with just a `main.nf` so I added `nextflow.config` with singularity scope and parameter scope. Lets continue to use this for future builds to avoid this problem going forward.
3. The execution instructions needed detail, I added instructions for downloading the test data, executing the pipeline and explaining what the flags do 
4. We don't want to clog up this repo so I removed the data and replaced it with instructions to download test data from existing bio-test-datasets repo
5. I removed old task `main.nf` files. We just want to build functionality and work on the fastqc pipeline so no need to store old examples, we can find these in old commits on github if needed. 
6. Hashed out all the lines of all supplementary `configs/` to prevent nextflow from trying to apply these files to your workflow.
7. Added an [outputs block](https://www.nextflow.io/docs/latest/process.html#outputs) to the process scope so we can pick up any outputs in a channel 

A few things for you to do before we can merge these changes and move onto the next task: 
1. Change the * in the outputs block to multiple distinct outputs to collect individual outputs into individual channels. Take a look at the [emit](https://nextflow.io/docs/edge/dsl2.html#process-named-output) option for how to do this 
2. Change the workflow diagram to explain what the fastqc workflow is doing, rather than what nextflow is doing. See [here](https://github.com/Sydney-Informatics-Hub/bamQC-nf), [here](https://github.com/Sydney-Informatics-Hub/Germline-ShortV) and [here](https://github.com/Sydney-Informatics-Hub/Somatic-ShortV) for examples of how we've done it for other pipelines.
3. Test the run command in the README.md works 
4. Let me know if theres anything that needs clarifying in the changes I've made

2023-10-23 02:56 UTC, georgiesamaha requested changes
Have added comments to changes made so you can see what happened and why. As you go through can you resolve comments you're ok with and let me know if there are any that are unclear before you proceed with changes requested in the previous comment.

2023-10-23 02:56 UTC, georgiesamaha commented on .gitignore
> +bio-test-datasets/
I added this to ensure we dont bload this repo with test data. Instructions on how to download have been added to readme.

2023-10-23 02:56 UTC, georgiesamaha commented on README.md
> +
Changed the description to focus on the pipeline we're building rather than nextflow and clarify it is under development.

2023-10-23 02:56 UTC, georgiesamaha commented on README.md
> +* [Singularity installation instructions](https://docs.sylabs.io/guides/3.0/user-guide/installation.html)
Added instructions for environment set up to ensure users/testers have dependencies installed before trying to run the workflow.

2023-10-23 02:56 UTC, georgiesamaha commented on README.md
> +```
This replaces need to store data in this repo.

2023-10-23 02:56 UTC, georgiesamaha commented on README.md
> +```
Added instructions for executing the workflow with an example for clarity.

2023-10-23 02:56 UTC, georgiesamaha commented on README.md
> +* `--output` name a directory to output the fastqc files to
Added explanation of what the flags do and how to use them.

2023-10-23 02:56 UTC, georgiesamaha commented on config/gadi.config
Hashed everything out as Nextflow searches for configs to apply.

2023-10-23 02:56 UTC, georgiesamaha commented on config/nimbus.config
Hashed everything out as Nextflow searches for configs to apply.

2023-10-23 02:56 UTC, georgiesamaha commented on config/setonix.config
Hashed everything out as Nextflow searches for configs to apply.

2023-10-23 02:56 UTC, georgiesamaha commented on config/standard.config
Hashed everything out as Nextflow searches for configs to apply.

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +F A S T Q C - N F
Named the pipeline

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +Find documentation @ https://github.com/Sydney-Informatics-Hub/fastqc-nf
Added url for git repo

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +outDir      : ${params.output}
Changed parameters for your specific application

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +  Usage:  nextflow run main.nf --fq <fq file> --output <directory_name>
Added example run command in help message

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +if ( params.help || params.fq == false ){
Changed conditions of running the help message. Will run if fq flag not provided.

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +if ( params.help || params.fq == false ){
Will also exit and not try to proceed.

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +fq = Channel.fromPath(params.fq)
Wrote functioning channel that takes fastq inputs provided by flag `--fq`

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +fastqc(fq)
Added process for running fastqc on fq input files.

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +outDir      : ${params.output}
Edited completion message for relevant variable.

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +    publishDir "${params.output}", mode: 'symlink'
Publish outputs to your specified outdir with `--output`

2023-10-23 02:56 UTC, georgiesamaha commented on main.nf
> +    publishDir "${params.output}", mode: 'symlink'
Can change mode to copy instead of symlink if needed. See [here](https://nextflow.io/docs/edge/process.html#publishdir)

2023-10-23 02:56 UTC, georgiesamaha commented on nextflow.config
Had to add nextflow.config to run singularity and specify params.

2023-10-25 04:33 UTC, chlu0571 commented
The script and container have been confirmed and run perfectly.

2023-10-25 04:33 UTC, closed without merging